name: test

on:
  pull_request:
    branches:
      - master
      - development
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Set Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # yarn install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test # yarn test
